name: Goodreads API Integration

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Build the app
        run: |
          npm install
          npm run build

      - name: Verify Goodreads API interactions in the build
        run: npm run build:verify-api
        env:
          GREADY_GOODREADS_API_KEY: ${{ secrets.GREADY_GOODREADS_API_KEY }}
